name: gurps_incantation_magic_model
version: 0.0.1
description: >
  This module contains the model that implements the GURPS Dungeon Fantasy Incantation Magic system.
author: M. Jeff Wilson <geek.macbeer@gmail.com>
homepage: http://hypermediocrity.us
documentation:
dependencies:
  built_value:
  range:

dev_dependencies:
  test: '>=0.12.0'
  mockito:

dependency_overrides:

environment:
  sdk: ">=1.22.0"